<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'phario\\phive\\aliasresolvertest' => '/services/phar/AliasResolverTest.php',
                'phario\\phive\\anyversionconstrainttest' => '/shared/versionconstraints/AnyVersionConstraintTest.php',
                'phario\\phive\\commandlocatortest' => '/CommandLocatorTest.php',
                'phario\\phive\\curlconfigtest' => '/shared/curl/CurlConfigTest.php',
                'phario\\phive\\curlresponsetest' => '/shared/curl/CurlResponseTest.php',
                'phario\\phive\\environmenttest' => '/shared/EnvironmentTest.php',
                'phario\\phive\\exactversionconstrainttest' => '/shared/versionconstraints/ExactVersionConstraintTest.php',
                'phario\\phive\\gnupgkeydownloadertest' => '/services/key/gpg/GnupgKeyDownloaderTest.php',
                'phario\\phive\\gnupgkeyimportertest' => '/services/key/gpg/GnupgKeyImporterTest.php',
                'phario\\phive\\gnupgsignatureverifiertest' => '/services/signature/gpg/GnupgSignatureVerifierTest.php',
                'phario\\phive\\gnupgverificationresulttest' => '/services/signature/gpg/GnupgVerificationResultTest.php',
                'phario\\phive\\greaterthanorequaltoversionconstrainttest' => '/shared/versionconstraints/GreaterThanOrEqualToVersionConstraintTest.php',
                'phario\\phive\\keyimportresulttest' => '/services/key/KeyImportResultTest.php',
                'phario\\phive\\keyservicetest' => '/services/key/KeyServiceTest.php',
                'phario\\phive\\pharaliastest' => '/shared/PharAliasTest.php',
                'phario\\phive\\phardownloadertest' => '/services/phar/PharDownloaderTest.php',
                'phario\\phive\\pharfiletest' => '/shared/PharFileTest.php',
                'phario\\phive\\phariorepositorylisttest' => '/shared/PharIoRepositoryListTest.php',
                'phario\\phive\\pharrepositorytest' => '/shared/repository/PharRepositoryTest.php',
                'phario\\phive\\pharservicetest' => '/services/phar/PharServiceTest.php',
                'phario\\phive\\phartest' => '/shared/PharTest.php',
                'phario\\phive\\scalartestdataprovider' => '/ScalarTestDataProvider.php',
                'phario\\phive\\signatureservicetest' => '/services/signature/SignatureServiceTest.php',
                'phario\\phive\\skelcommandconfigtest' => '/commands/skel/SkelCommandConfigTest.php',
                'phario\\phive\\specificmajorandminorversionconstrainttest' => '/shared/versionconstraints/SpecificMajorAndMinorVersionConstraintTest.php',
                'phario\\phive\\specificmajorversionconstrainttest' => '/shared/versionconstraints/SpecificMajorVersionConstraintTest.php',
                'phario\\phive\\teststreamwrapper' => '/TestStreamWrapper.php',
                'phario\\phive\\urltest' => '/shared/UrlTest.php',
                'phario\\phive\\versionconstraintgrouptest' => '/shared/versionconstraints/VersionConstraintGroupTest.php',
                'phario\\phive\\versionconstraintparsertest' => '/shared/versionconstraints/VersionConstraintParserTest.php',
                'phario\\phive\\versiontest' => '/shared/VersionTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    true
);
// @codeCoverageIgnoreEnd
