<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'phario\\phive\\abstractversionconstrainttest' => '/unit/shared/versionconstraints/AbstractVersionConstraintTest.php',
                'phario\\phive\\aliasresolvertest' => '/unit/services/phar/AliasResolverTest.php',
                'phario\\phive\\anyversionconstrainttest' => '/unit/shared/versionconstraints/AnyVersionConstraintTest.php',
                'phario\\phive\\checksumservicetest' => '/unit/services/checksum/ChecksumServiceTest.php',
                'phario\\phive\\commandlocatortest' => '/unit/CommandLocatorTest.php',
                'phario\\phive\\curlconfigtest' => '/unit/shared/http/CurlConfigTest.php',
                'phario\\phive\\directorytest' => '/unit/shared/DirectoryTest.php',
                'phario\\phive\\environmenttest' => '/unit/shared/EnvironmentTest.php',
                'phario\\phive\\exactversionconstrainttest' => '/unit/shared/versionconstraints/ExactVersionConstraintTest.php',
                'phario\\phive\\factorytest' => '/unit/FactoryTest.php',
                'phario\\phive\\filenametest' => '/unit/shared/FilenameTest.php',
                'phario\\phive\\filetest' => '/unit/shared/FileTest.php',
                'phario\\phive\\githubreleasesrepositorytest' => '/unit/GithubReleasesRepositoryTest.php',
                'phario\\phive\\gnupgkeydownloadertest' => '/unit/services/key/gpg/GnupgKeyDownloaderTest.php',
                'phario\\phive\\gnupgkeyimportertest' => '/unit/services/key/gpg/GnupgKeyImporterTest.php',
                'phario\\phive\\gnupgsignatureverifiertest' => '/unit/services/signature/gpg/GnupgSignatureVerifierTest.php',
                'phario\\phive\\gnupgverificationresulttest' => '/unit/services/signature/gpg/GnupgVerificationResultTest.php',
                'phario\\phive\\greaterthanorequaltoversionconstrainttest' => '/unit/shared/versionconstraints/GreaterThanOrEqualToVersionConstraintTest.php',
                'phario\\phive\\httpresponsetest' => '/unit/shared/http/HttpResponseTest.php',
                'phario\\phive\\installcommandconfigtest' => '/unit/commands/install/InstallCommandConfigTest.php',
                'phario\\phive\\installcommandtest' => '/unit/commands/install/InstallCommandTest.php',
                'phario\\phive\\keyimportresulttest' => '/unit/services/key/KeyImportResultTest.php',
                'phario\\phive\\keyservicetest' => '/unit/services/key/KeyServiceTest.php',
                'phario\\phive\\pharaliastest' => '/unit/shared/PharAliasTest.php',
                'phario\\phive\\phardownloadertest' => '/unit/services/phar/PharDownloaderTest.php',
                'phario\\phive\\pharservicetest' => '/unit/services/phar/PharServiceTest.php',
                'phario\\phive\\phartest' => '/unit/shared/PharTest.php',
                'phario\\phive\\phiveinstalldbtest' => '/unit/shared/repository/PhiveInstallDBTest.php',
                'phario\\phive\\purgecommandconfigtest' => '/unit/commands/purge/PurgeCommandConfigTest.php',
                'phario\\phive\\purgecommandtest' => '/unit/commands/purge/PurgeCommandTest.php',
                'phario\\phive\\requestedphartest' => '/unit/commands/install/RequestedPharTest.php',
                'phario\\phive\\resetcommandconfigtest' => '/unit/commands/reset/ResetCommandConfigTest.php',
                'phario\\phive\\resetcommandtest' => '/unit/commands/reset/ResetCommandTest.php',
                'phario\\phive\\scalartestdataprovider' => '/unit/ScalarTestDataProvider.php',
                'phario\\phive\\sha1hashtest' => '/unit/shared/hash/sha/Sha1HashTest.php',
                'phario\\phive\\sha256hashtest' => '/unit/shared/hash/sha/Sha256HashTest.php',
                'phario\\phive\\signatureservicetest' => '/unit/services/signature/SignatureServiceTest.php',
                'phario\\phive\\skelcommandconfigtest' => '/unit/commands/skel/SkelCommandConfigTest.php',
                'phario\\phive\\sourceslisttest' => '/unit/shared/SourcesListTest.php',
                'phario\\phive\\specificmajorandminorversionconstrainttest' => '/unit/shared/versionconstraints/SpecificMajorAndMinorVersionConstraintTest.php',
                'phario\\phive\\specificmajorversionconstrainttest' => '/unit/shared/versionconstraints/SpecificMajorVersionConstraintTest.php',
                'phario\\phive\\teststreamwrapper' => '/unit/TestStreamWrapper.php',
                'phario\\phive\\unsupportedhashstub' => '/unit/services/checksum/stubs/UnsupportedHashStub.php',
                'phario\\phive\\updatecommandconfigtest' => '/unit/commands/update/UpdateCommandConfigTest.php',
                'phario\\phive\\updatecommandtest' => '/unit/commands/update/UpdateCommandTest.php',
                'phario\\phive\\urltest' => '/unit/shared/UrlTest.php',
                'phario\\phive\\versionconstraintgrouptest' => '/unit/shared/versionconstraints/VersionConstraintGroupTest.php',
                'phario\\phive\\versionconstraintparsertest' => '/unit/shared/versionconstraints/VersionConstraintParserTest.php',
                'phario\\phive\\versiontest' => '/unit/shared/VersionTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    true
);
// @codeCoverageIgnoreEnd
