<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\phive\\cli' => '/CLI.php',
                'theseer\\phive\\clicommandoptions' => '/CLICommandOptions.php',
                'theseer\\phive\\clicommandoptionsexception' => '/CLICommandOptionsException.php',
                'theseer\\phive\\clirequest' => '/CLIRequest.php',
                'theseer\\phive\\coloredconsolelogger' => '/shared/logger/ColoredConsoleLogger.php',
                'theseer\\phive\\commandinterface' => '/commands/CommandInterface.php',
                'theseer\\phive\\commandlocator' => '/commands/CommandLocator.php',
                'theseer\\phive\\commandlocatorexception' => '/commands/CommandLocatorException.php',
                'theseer\\phive\\consolelogger' => '/shared/logger/ConsoleLogger.php',
                'theseer\\phive\\curl' => '/shared/curl/Curl.php',
                'theseer\\phive\\curlexception' => '/shared/curl/CurlException.php',
                'theseer\\phive\\curlresponse' => '/shared/curl/CurlResponse.php',
                'theseer\\phive\\factory' => '/Factory.php',
                'theseer\\phive\\gnupgkeydownloader' => '/shared/keyservice/gpg/GnupgKeyDownloader.php',
                'theseer\\phive\\gnupgkeyimporter' => '/shared/keyservice/gpg/GnupgKeyImporter.php',
                'theseer\\phive\\gnupgkeyring' => '/shared/keyservice/gpg/GnupgKeyRing.php',
                'theseer\\phive\\gnupgsignatureverifier' => '/shared/signature/gpg/GnupgSignatureVerifier.php',
                'theseer\\phive\\gnupgverificationresult' => '/shared/signature/gpg/GnupgVerificationResult.php',
                'theseer\\phive\\helpcommand' => '/commands/help/HelpCommand.php',
                'theseer\\phive\\installcommand' => '/commands/install/InstallCommand.php',
                'theseer\\phive\\installcommandconfig' => '/commands/install/InstallCommandConfig.php',
                'theseer\\phive\\installservice' => '/commands/install/InstallService.php',
                'theseer\\phive\\keydownloaderinterface' => '/shared/keyservice/KeyDownloaderInterface.php',
                'theseer\\phive\\keyimporterinterface' => '/shared/keyservice/KeyImporterInterface.php',
                'theseer\\phive\\keyringinterface' => '/shared/keyservice/KeyRingInterface.php',
                'theseer\\phive\\keyservice' => '/shared/keyservice/KeyService.php',
                'theseer\\phive\\loggerinterface' => '/shared/logger/LoggerInterface.php',
                'theseer\\phive\\phardownloader' => '/commands/install/PharDownloader.php',
                'theseer\\phive\\pharfile' => '/commands/install/PharFile.php',
                'theseer\\phive\\pharioclient' => '/commands/install/PharIoClient.php',
                'theseer\\phive\\signatureservice' => '/shared/signature/SignatureService.php',
                'theseer\\phive\\signatureverifierinterface' => '/shared/signature/SignatureVerifierInterface.php',
                'theseer\\phive\\url' => '/shared/Url.php',
                'theseer\\phive\\verificationfailedexception' => '/shared/signature/VerificationFailedException.php',
                'theseer\\phive\\version' => '/commands/version/Version.php',
                'theseer\\phive\\versioncommand' => '/commands/version/VersionCommand.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
